#theme: jekyll-theme-cayman
remote_theme: pages-themes/minimal@v0.2.0
plugins: - jekyll-remote-theme # add this line to the plugins list if you already have one
title: Chitra Javdekar, Ph.D.
description: Personal webpage

#Enter the following platform usernames if you would like them to appear on your website
owner:
  name: Chitra Javdekar
  avatar: chitra-linkedin.png
  email: chitra.javdekar@gmail.com
  # Do not include the @ symbol in your Twitter username
  twitter: cdeshpan
  #linkedin: #username
